# Site settings
title: "Stanford Climate Influencer Program"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
program:
    name: Stanford Climate Influencer Program
    description: Despite the importance of the climate crisis, most people feel powerless and unsure about how to make a difference. We have been developing some ideas for empowering you and others like you to have a bigger impact and directly inspire action in policy makers. Join us and fight against climate crisis with your leadership! 
    signup: https://docs.google.com/forms/d/e/1FAIpQLSfJDWQ64snme56JIL79A6n2vEm9FUsRP1ZPmFQD30QwBMOrCg/viewform

contact:
    email: climatecrisis@cs.stanford.edu 
    twitter: https://twitter.com/stanfordclimate 
    github: https://github.com/StanfordClimateInfluencer
    

